#+TITLE: =DASHit=: Automated design of Cas9 guide RNAs for DASH experiments
#+AUTHOR: David Dynerman
#+EMAIL: david.dynerman@czbiohub.org
#+OPTIONS: toc:nil num:nil

=DASHit= is a collection of software for the automated design and
evaluation of Cas9 guide RNAs for DASH experiments.

* Installation
=DASHit= runs on Linux and macOS. Installing =DASHit= requires:

1. A C++ compiler that supports C++11, e.g., a recent version of =g++= or =clang=
2. =go= version 1.9 or later
3. =python3=

To install:

#+BEGIN_SRC bash
git clone https://github.com/czbiohub/dashit
cd dashit
python3 -m venv ~/.virtualenvs/dashit
source ~/.virtualenvs/dashit/bin/activate
make install
#+END_SRC

By default this will install compiled binaries into
=/usr/local/bin=. To specify a different location for these compiled
binaries, set =PREFIX=, e.g.,

#+begin_src bash
PREFIX=$HOME make install
#+end_src

*Note:* At least the =offtarget= binary must be in your =PATH= in
order for =dashit_filter= to work.

* Documentation
Please visit [[https://dashit.czbiohub.org][https://dashit.czbiohub.org]] for documentation and examples.

* License
Copyright 2019 Chan-Zuckerberg Biohub

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

** Previous versions
Old versions of DASHit (pre 2.0), were licensed under the hybrid [[./old-dashit-1.0-license.md][Biohub
License]], which was free for non-profit use, but required a separate
agreement for commercial use.
